# AUTOGENERATED! DO NOT EDIT! File to edit: nbdev_nbs/nbdev_nbs/_utils.ipynb (unless otherwise specified).

__all__ = ['tqdm_wrapper', 'train_callback']

# Cell
import tqdm
import functools

def tqdm_wrapper(pbar:tqdm.tqdm, update:float, epoch, nAA, batch, loss) -> None:
    """Update a qdm progress bar.
    Args:
        pbar (type): a tqd, .tqdm objet.
        update (float): The new value for the progressbar.
    """
    current_value = pbar.n
    delta = update - current_value
    pbar.update(delta)
    pbar.set_description(f'Epoch={epoch+1}, nAA={nAA}, Batch={batch}, Loss={loss:.4f}' )

def train_callback():
    return functools.partial(tqdm_wrapper, tqdm.tqdm(total=1))
