# AUTOGENERATED! DO NOT EDIT! File to edit: nbdev_nbs/nbdev_nbs/_utils.ipynb (unless otherwise specified).

__all__ = ['tqdm_wrapper', 'train_callback', 'str_to_int']

# Cell
import tqdm
import functools
import numba

def tqdm_wrapper(pbar:tqdm.tqdm, update:float, epoch, nAA, batch, loss) -> None:
    """Update a qdm progress bar.
    Args:
        pbar (type): a tqd, .tqdm objet.
        update (float): The new value for the progressbar.
    """
    current_value = pbar.n
    delta = update - current_value
    pbar.update(delta)
    pbar.set_description(f'Epoch={epoch+1}, nAA={nAA}, Batch={batch}, Loss={loss:.4f}' )

def train_callback():
    return functools.partial(tqdm_wrapper, tqdm.tqdm(total=1))


# Cell
@numba.njit
def str_to_int(s):
    if s.startswith('-'):
        neg = True
        s = s[1:]
    else:
        neg = False
    final_index, result = len(s) - 1, 0
    for i,v in enumerate(s):
        result += (ord(v) - 48) * (10 ** (final_index - i))
    if neg:
        return -result
    else:
        return result