# AUTOGENERATED! DO NOT EDIT! File to edit: nbdev_nbs/psm_reader/alphapept_reader.ipynb (unless otherwise specified).

__all__ = ['parse_ap', 'get_x_tandem_score', 'AlphaPeptReader']

# Cell
import numba
import os
import pandas as pd
import numpy as np
import h5py

from alphadeep.psm_reader.psm_reader import (
    PSMReaderBase, psm_reader_provider
)
from alphadeep.model.ccs import mobility_to_ccs_df

@numba.njit
def parse_ap(precursor):
    """
    Parser to parse peptide strings
    """
    items = precursor.split('_')
    if len(items) == 3:
        decoy = 1
    else:
        decoy = 0
    modseq = items[0]
    charge = items[-1]

    parsed = []
    mods = []
    sites = []
    string = ""

    if modseq[0] == 'a':
        sites.append('0')
        mods.append('a')
        modseq = modseq[1:]
    elif modseq.startswith('tmt'):
        for l in range(3, len(modseq)):
            if modseq[l].isupper():
                break
        sites.append('0')
        mods.append(modseq[:l])
        modseq = modseq[l:]

    for i in modseq:
        string += i
        if i.isupper():
            parsed.append(i)
            if len(string) > 1:
                sites.append(str(len(parsed)))
                mods.append(string)
            string = ""

    return ''.join(parsed), ';'.join(mods), ';'.join(sites), charge, decoy

def get_x_tandem_score(df: pd.DataFrame) -> np.ndarray:
    b = df['b_hits'].astype('int').apply(lambda x: np.math.factorial(x)).values
    y = df['y_hits'].astype('int').apply(lambda x: np.math.factorial(x)).values
    x_tandem = np.log(b.astype('float')*y.astype('float')*df['matched_int'].values)

    x_tandem[x_tandem==-np.inf] = 0

    return x_tandem

class AlphaPeptReader(PSMReaderBase):
    def __init__(self):
        super().__init__()

        self.modification_convert_dict['cC'] = 'Carbamidomethyl@C'
        self.modification_convert_dict['oxM'] = 'Oxidation@M'
        self.modification_convert_dict['pS'] = 'Phospho@S'
        self.modification_convert_dict['pT'] = 'Phospho@T'
        self.modification_convert_dict['pY'] = 'Phospho@Y'
        self.modification_convert_dict['a'] = 'Acetyl@Protein N-term'

        self.column_mapping = {
            'rt':'rt',
            'rt_norm': 'rt_norm',
            'spec_idx': ['scan_no','raw_idx'],
            'query_id': 'query_idx',
            'mobility': 'mobility',
            'score': 'x_tandem',
            'charge': 'charge',
            'raw_name': 'raw_name',
        }

    def _load_file(self, filename):
        if self.keep_all_psm:
            hdf_dataset = 'second_search'
        else:
            hdf_dataset = 'peptide_fdr'
        with h5py.File(filename, 'r') as _hdf:
            dataset = _hdf[hdf_dataset]
            df = pd.DataFrame({col:dataset[col] for col in dataset.keys()})
            df['raw_name'] = os.path.basename(filename)[:-len('.ms_data.hdf')]
            df['precursor'] = df['precursor'].str.decode('utf-8')
            if 'scan_no' in df.columns:
                df['scan_no'] = df['scan_no'].astype('int')
            df['charge'] = df['charge'].astype(int)
            df['rt_norm'] = df.rt/df.rt.max()

            df['x_tandem'] = get_x_tandem_score(df)

        return df

    def _translate_columns(self, df: pd.DataFrame):
        super()._translate_columns(df)
        (
            self._psm_df['sequence'], self._psm_df['mods'],
            self._psm_df['mod_sites'], _charges,
            self._psm_df['decoy']
        ) = zip(*df['precursor'].apply(parse_ap))
        self._psm_df.decoy = self._psm_df.decoy.astype(int)

    def _post_process(self, filename: str, origin_df: pd.DataFrame):
        super()._post_process(filename, origin_df)
        if 'mobility' in self._psm_df:
            self._psm_df = mobility_to_ccs_df(self._psm_df)


psm_reader_provider.register_reader('alphapept', AlphaPeptReader)