# Build and publish Docker image
name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag_to_release:
        description: 'Enter tag to release (example: v1.5.5). A tag with this name must exist in the repository.'
        type: string
        required: true

jobs:
  publish_on_pypi:
    uses: MannLabs/alphashared/.github/workflows/publish_docker.yml@v1
    secrets:
      docker_access_token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
    with:
      package_name: peptdeep
      tag_to_release: ${{ inputs.tag_to_release }}
